name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        # Create a new tag
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        run: |
          git tag v1.0.${{ github.run_number }}
          git push --tags ${{ github.repository }} ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            - ./
            - ./**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}